openAOD/Python-PatternHouse

Numeric Patterns/Source Code/numeric_pattern1.py
**script name:** Python Numeric Pattern 1
**Changes I made:**
created script and README file
**Issue no. :** #310 
**acknowledgement**
I have tested the script and distributing it under MIT license.
=> Done Python Numeric Pattern 1 (#310)

Numeric Patterns/CodeFiles/Pattern7.py, Numeric Patterns/CodeFiles/Pattern8.py
**Scripts name:** 
- Python Numeric Pattern 7
- Python Numeric Pattern 8
**Changes I made:**
created scripts
**Issues no. :**
- #316 
- #317 
**Acknowledgement**
I have tested the scripts and distributing it under MIT license.
=> Python Numeric Pattern

Numeric Patterns/CodeFiles/Pattern10.py, Numeric Patterns/CodeFiles/Pattern11.py, Numeric Patterns/CodeFiles/Pattern9.py
**Scripts name:** 
- Python Numeric Pattern 9
- Python Numeric Pattern 10
- Python Numeric Pattern 11
**Changes I made:**
created scripts
**Issues no. :**
- #318 
- #319 
- #320 
**Acknowledgement**
I have tested the scripts and distributing it under MIT license.
=> Python numeric

Numeric Patterns/CodeFiles/Pattern15.py, Numeric Patterns/CodeFiles/Pattern16.py, Numeric Patterns/CodeFiles/Pattern17.py
**Scripts name:** 
- Python Numeric Pattern 15
- Python Numeric Pattern 16
- Python Numeric Pattern 17
**Changes I made:**
created scripts
**Issues no. :**
- #324 
- #325 
- #326  
**Acknowledgement**
I have tested the scripts and distributing it under MIT license.
@aryashah2k
=> Python numeric patterns

String Patterns/stringpattern10.py, String Patterns/stringpattern11.py, String Patterns/stringpattern12.py, String Patterns/stringpattern2.py, String Patterns/stringpattern3.py, String Patterns/stringpattern4.py, String Patterns/stringpattern5.py, String Patterns/stringpattern6.py, String Patterns/stringpattern7.py, String Patterns/stringpattern8.py, String Patterns/stringpattern9.py
Solutions to string patterns 2-12
Resolves #21, Resolves #17, Resolves #16, Resolves #22, Resolves #19, Resolves #20, Resolves #18, Resolves #15, Resolves #14, Resolves #12, Resolves #13
=> String patterns 2-12

Alphabetic Patterns/alphabeticpattern12.py, Alphabetic Patterns/alphabeticpattern13.py, Alphabetic Patterns/alphabeticpattern14.py, Alphabetic Patterns/alphabeticpattern16.py, Alphabetic Patterns/alphabeticpattern17.py, Alphabetic Patterns/alphabeticpattern18.py, Alphabetic Patterns/alphabeticpattern24.py, Alphabetic Patterns/alphabeticpattern32.py, Alphabetic Patterns/alphabeticpattern38.py, Alphabetic Patterns/alphabeticpattern45.py
Scripts name:
Python Alphabetic Pattern 
Changes I made:
Created Scripts
Issues no. :
Code | Alphabetic Pattern 12 #130 
Code | Alphabetic Pattern 13 #131 
Code | Alphabetic Pattern 14 #132 
Code | Alphabetic Pattern 16 #134 
Code | Alphabetic Pattern 17 #135 
Code | Alphabetic Pattern 18 #136 
Code | Alphabetic Pattern 24 #142 
Code | Alphabetic Pattern 32 #150 
Code | Alphabetic Pattern 38 #156 
Code | Alphabetic Pattern 45 #163 
Acknowledgement
I have tested the scripts and distributing it under MIT license.
=> Alphabetic Patterns - Python

Symbol Patterns/symbolpattern107.py, Symbol Patterns/symbolpattern108.py, Symbol Patterns/symbolpattern109.py, Symbol Patterns/symbolpattern110.py, Symbol Patterns/symbolpattern111.py, Symbol Patterns/symbolpattern112.py, Symbol Patterns/symbolpattern113.py, Symbol Patterns/symbolpattern114.py, Symbol Patterns/symbolpattern115.py, Symbol Patterns/symbolpattern116.py
@aryashah2k 
solution to symbol patterns 107-116 in python
=> Pattern106 116

Numeric Patterns/numericpattern41.py, Numeric Patterns/numericpattern44.py, Numeric Patterns/numericpattern45.py, Numeric Patterns/numericpattern48.py, Numeric Patterns/numericpattern49.py, Numeric Patterns/numericpattern50.py, Numeric Patterns/numericpattern57.py, Numeric Patterns/numericpattern58.py, Numeric Patterns/numericpattern59.py, Numeric Patterns/numericpattern60.py
#350  #353 #354  #357  #358 #359  #366  #367  #368  #369
=> Solved various issues

Symbol Patterns/symbolicpattern30.py, Symbol Patterns/symbolicpattern31.py, Symbol Patterns/symbolicpattern33.py, Symbol Patterns/symbolicpattern34.py, Symbol Patterns/symbolicpattern36.py, Symbol Patterns/symbolicpattern37.py, Symbol Patterns/symbolicpattern38.py, Symbol Patterns/symbolicpattern39.py, Symbol Patterns/symbolicpattern40.py, Symbol Patterns/symbolicpattern41.py, Symbol Patterns/symbolicpattern42.py, Symbol Patterns/symbolicpattern43.py, Symbol Patterns/symbolicpattern44.py, Symbol Patterns/symbolicpattern45.py, Symbol Patterns/symbolicpattern46.py, Symbol Patterns/symbolicpattern47.py, Symbol Patterns/symbolicpattern48.py, Symbol Patterns/symbolicpattern49.py, Symbol Patterns/symbolicpattern50.py, Symbol Patterns/symbolicpattern51.py
These issues are resolved:
#667 #668 #670 #671 #673 #674 #675 #676 #677 #678 #679 #680 #681 #682 #683 #684
#685 #686 #687 #688
=> Various issues resolved

Pyramid Patterns/pyramidpattern10.py, Pyramid Patterns/pyramidpattern11.py, Pyramid Patterns/pyramidpattern13.py, Pyramid Patterns/pyramidpattern14.py, Pyramid Patterns/pyramidpattern15.py, Pyramid Patterns/pyramidpattern16.py, Pyramid Patterns/pyramidpattern17.py, Pyramid Patterns/pyramidpattern18.py, Pyramid Patterns/pyramidpattern19.py, Pyramid Patterns/pyramidpattern2.py, Pyramid Patterns/pyramidpattern20.py, Pyramid Patterns/pyramidpattern21.py, Pyramid Patterns/pyramidpattern3.py, Pyramid Patterns/pyramidpattern4.py, Pyramid Patterns/pyramidpattern5.py, Pyramid Patterns/pyramidpattern7.py, Pyramid Patterns/pyramidpattern8.py, Pyramid Patterns/pyramidpattern9.py
Solved from pyramid pattern 2 - pyramid pattern 21
=> Solved 20 issues

Alphabetic Patterns/alphabeticpattern19.py, Alphabetic Patterns/alphabeticpattern20.py, Alphabetic Patterns/alphabeticpattern21.py, Alphabetic Patterns/alphabeticpattern23.py, Alphabetic Patterns/alphabeticpattern25.py, Alphabetic Patterns/alphabeticpattern26.py, Alphabetic Patterns/alphabeticpattern7.py, Alphabetic Patterns/alphabeticpattern8.py, Pyramid Patterns/pyramidpattern61.py, Symbol Patterns/symbolicpattern162.py
fixes #799 #86 #125 #126 #137 #138 #139 #141 #143 #144 
Hey @aryashah2k Please review and merge the PR if there is no issue.
=> Committed codes for 10 patterns

Alphabetic Patterns/alphabeticpattern27.py, Alphabetic Patterns/alphabeticpattern29.py, Alphabetic Patterns/alphabeticpattern30.py, Alphabetic Patterns/alphabeticpattern31.py, Alphabetic Patterns/alphabeticpattern33.py, Alphabetic Patterns/alphabeticpattern34.py, Alphabetic Patterns/alphabeticpattern35.py, Alphabetic Patterns/alphabeticpattern36.py, Alphabetic Patterns/alphabeticpattern37.py, Alphabetic Patterns/alphabeticpattern39.py
Fixes #145 #147 #148 #149 #151 #152 #153 #154 #155 #157 
Hey, @aryashah2k I have written the codes for 10 more patterns. Please merge the PR if there is no issue.
Thankyou
=> Added Code for 10 More patterns

Symbol Patterns/symbolpattern154.py, Symbol Patterns/symbolpattern155.py, Symbol Patterns/symbolpattern156.py, Symbol Patterns/symbolpattern157.py, Symbol Patterns/symbolpattern158.py, Symbol Patterns/symbolpattern159.py, Symbol Patterns/symbolpattern160.py, Symbol Patterns/symbolpattern161.py, Symbol Patterns/symbolpattern67.py, Symbol Patterns/symbolpattern68.py
Resolved from 154 - 161 symbol pattern issues and 67 and 68 issue of the symbol pattern
=> Resolved issues

Pyramid Patterns/pyramidpattern22.py, Pyramid Patterns/pyramidpattern23.py, Pyramid Patterns/pyramidpattern24.py, Pyramid Patterns/pyramidpattern25.py, Pyramid Patterns/pyramidpattern29.py, Pyramid Patterns/pyramidpattern30.py, Pyramid Patterns/pyramidpattern31.py, Pyramid Patterns/pyramidpattern32.py, Pyramid Patterns/pyramidpattern33.py, Pyramid Patterns/pyramidpattern34.py, Pyramid Patterns/pyramidpattern35.py, Pyramid Patterns/pyramidpattern37.py, Pyramid Patterns/pyramidpattern38.py, Pyramid Patterns/pyramidpattern39.py, Pyramid Patterns/pyramidpattern40.py, Pyramid Patterns/pyramidpattern41.py, Pyramid Patterns/pyramidpattern42.py, Pyramid Patterns/pyramidpattern63.py
Solved from (22 - 26, 29-42, 63 ) pyramid pattern issues
=> Solved issues

Alphabetic Patterns/alphabeticpatter66.py, Alphabetic Patterns/alphabeticpattern60.py, Alphabetic Patterns/alphabeticpattern61.py, Alphabetic Patterns/alphabeticpattern62.py, Alphabetic Patterns/alphabeticpattern63.py, Alphabetic Patterns/alphabeticpattern64.py, Alphabetic Patterns/alphabeticpattern65.py, Alphabetic Patterns/alphabeticpattern67.py, Alphabetic Patterns/alphabeticpattern68.py, Alphabetic Patterns/pyramidpattern61.py
Fixes #178 #179 #180 #181 #182 #183 #184 #185 #186 #187 
Hey @aryashah2k I have created the PR please review and merge it if there are no issues.
Thank You
=> Solved Code for 10 More patterns

Alphabetic Patterns/alphabeticpattern70.py, Alphabetic Patterns/alphabeticpattern71.py, Alphabetic Patterns/alphabeticpattern72.py, Alphabetic Patterns/alphabeticpattern73.py, Alphabetic Patterns/alphabeticpattern74.py, Alphabetic Patterns/alphabeticpattern75.py, Alphabetic Patterns/alphabeticpattern76.py, Alphabetic Patterns/alphabeticpattern77.py, Alphabetic Patterns/alphabeticpattern78.py, Alphabetic Patterns/alphabeticpattern79.py
Fixes : #188 #189 #190 #191 #192 #193 #194 #195 #196 #197 
Hey @aryashah2k ,
Please review the PR and merge it if there are no issues.
=> Added codes for 10 more patterns

Numeric Patterns/numericpattern68.py, Numeric Patterns/numericpattern69.py, Numeric Patterns/numericpattern70.py, Numeric Patterns/numericpattern71.py, Numeric Patterns/numericpattern72.py, Numeric Patterns/numericpattern73.py, Numeric Patterns/numericpattern74.py, Numeric Patterns/numericpattern75.py, Numeric Patterns/numericpattern76.py, Numeric Patterns/numericpattern77.py
Hey @aryashah2k  Please check the code for 10 more solved patterns and if there is no issue please merge the PR.
Fixes: #377 #378 #379 #380 #381 #382 #383 #384 #385 #386
=> Solved Code for 10 more issues

Numeric Patterns/numericpattern39.py, Numeric Patterns/numericpattern78.py, Numeric Patterns/numericpattern79.py, Numeric Patterns/numericpattern80.py, Numeric Patterns/numericpattern81.py, Numeric Patterns/numericpattern82.py, Numeric Patterns/numericpattern83.py, Numeric Patterns/numericpattern84.py, Numeric Patterns/numericpattern85.py, Numeric Patterns/numericpattern86.py
Hey, @aryashah2k I have created the Pr for 10 more patterns. Please merge it if there is no issue.
Fixes: #348 #387 #388 #389 #390 #391 #392 #393 #394 #395 
Also, there are a few things I would like to clarify and mention -:
1. I am a SWOC participant, and I checked the discord messages today so I filled the pattern house Swag form today so will I be still eligible for that?
2.  I have also commented my PID in the SWOC Contributor sheet so please add my points there as well, also if you could tell me how can I see that for this particular project where do I stand that would be a great help.
3. According to the repo stats it just feels that I should be in the top 3 contributors I guess please correct me if I am wrong.
Thank you...
=> Solved Code for 10More patterns

Alphabetic Patterns/alphabeticpattern15.py, Alphabetic Patterns/alphabeticpattern22.py, Alphabetic Patterns/alphabeticpattern4.py, Alphabetic Patterns/alphabeticpattern41.py, Alphabetic Patterns/alphabeticpattern9.py, Numeric Patterns/numericpattern18.py, Pyramid Patterns/pyramidpattern93.py, Symbol Patterns/symbolicpattern103.py, Symbol Patterns/symbolicpattern104.py, Symbol Patterns/symbolicpattern93.py
#327 - Numeric Pattern 18
#159 - Alphabetic Pattern 41
#140 - Alphabetic Pattern 22
#133 - Alphabetic Pattern 15
#127 - Alphabetic Pattern 9
#122 - Alphabetic Pattern 4
#118 - Pyramid Pattern 93
#741 - Symbol Pattern 104
#740 - Symbol Pattern 103
#730 - Symbol Pattern 93
=> Additional Problems

Symbol Patterns/symbolicpattern170.py
symbolicpattern170 solved
if any problem please comment!
=> Symbol Pattern 170 #807

String Patterns/stringpattern1.py, String Patterns/stringpattern13.py, String Patterns/stringpattern14.py, String Patterns/stringpattern15.py
=> String patterns

Numeric Patterns/numericpattern232.py, Numeric Patterns/numericpattern233.py, Symbol Patterns/symbolicpattern169.py
Please comment if any problem!
=> Issue  Symbol Pattern 169, Numeric pattern 232 and 233 solved

Symbol Patterns/symbolicpattern180.py
=> Add symbol pattern 180

Symbol Patterns/symbolicpattern164.py
Solves symbols 164. Solves #801
=> Add symbols 164.
